#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

fpath+=~/.zfunc

# Support for starship zprezto theme
setopt prompt_subst interactive_comments

# load the appropriate kitty theme
kitty_reload() {
    export DARK_MODE="$(dark-mode status)"

    # check if kitty is active
    if [[ -n "$KITTY_PID" ]]; then
        # set dark theme
        if [[ "$DARK_MODE" == "on" ]]; then
            kitty @ set-colors --all --configured "$HOME/.config/kitty/theme-dark.conf"
        else
            kitty @ set-colors --all --configured "$HOME/.config/kitty/theme-light.conf"
        fi
    fi
}

# check if kitty is running but we are not in neovim
if [[ -n "$KITTY_PID" && -z "$NVIM" ]]; then
    kitty_reload
fi

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# fzf key bindings
[ -f $HOME/.dotfiles/fzf.zsh ] && source $HOME/.dotfiles/fzf.zsh

# fzf opts
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Options to fzf command
export FZF_COMPLETION_OPTS='--border --info=inline'

# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

# Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf --preview 'erd -C force -H -I -L 1 {} | head -200' "$@" ;;
    export|unset) fzf --preview "eval 'echo \$'{}"                       "$@" ;;
    ssh)          fzf --preview 'dog --color=always {}'                  "$@" ;;
    *)            fzf --preview 'bat -n --color=always {}'               "$@" ;;
  esac
}

eval "$(atuin init zsh --disable-up-arrow)"
